import { Poppins } from "next/font/google";
import "./globals.css";


const poppinsFont = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: '500'
});



export const metadata = {
  title: "SOS AMBULANCE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body className={`${poppinsFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
